#seed: 0
phase: 1

train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ../datasets/train/DIV2K/HR_aug_sub128 ### set path
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 32 # lr, only for train
      scale: [4,4] # range
      augment: [hflip, vflip, dflip]
  batch_size: 16 # total
  num_workers: 4 # total

valid_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ../datasets/valid/DIV2K/HR ### set path
  wrapper:
    name: sr-implicit-downsampled
    args:
      scale: null
  scales: [4]

test_dataset:
  dataset:
    name: image-folder
    args:
      root_path: null
  wrapper:
    name: sr-implicit-downsampled
    args:
      scale: null

psnr_type: rgb
patch_size: 32
step: 28

data_norm:
  mean: [0.4488, 0.4371, 0.4040]
  std : [1.0, 1.0, 1.0]

model:
  name: pcsr-phase1
  args:
    encoder_spec:
      name: carn
      args:
        nf: 52
        no_upsampling: true

    heavy_sampler_spec:
      name: liif-sampler
      args:
        imnet_spec:
          name: mlp
          args:    
            hidden_list: [74,74,74,74]

    light_sampler_spec:
      name: liif-sampler
      args:
        imnet_spec:
          name: mlp
          args:
            hidden_list: [20,20,20] #
    
    classifier_spec:
      name: liif-sampler
      args:
        imnet_spec:
          name: mlp
          args:
            hidden_list: [10,10] #

loss_rgb_w: 1000
loss_avg_w: 3

optimizer:
  name: adam
  args:
    lr: 2.e-4
    betas: [0.9, 0.99]
    weight_decay: 0

lr_scheduler:
  name: CosineAnnealingLR_Restart
  args:
    T_period: [500000]
    restarts: [500000]
    weights: [1]
    eta_min: 1.e-7

iter_max: 500000
iter_print: 1000
iter_val: 100000
iter_save: 100000
